"""empty message

Revision ID: 16fee2735b75
Revises: a224e18bd53f
Create Date: 2022-04-24 22:05:40.842896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16fee2735b75'
down_revision = 'a224e18bd53f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_access_log', sa.Column('create_date', sa.DateTime(), nullable=False))
    op.add_column('user_log', sa.Column('create_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_log', 'create_date')
    op.drop_column('file_access_log', 'create_date')
    # ### end Alembic commands ###
